-- MySQL Script generated by MySQL Workbench
-- Sat Dec 28 19:22:46 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema gser_db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `gser_db` ;

-- -----------------------------------------------------
-- Schema gser_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gser_db` DEFAULT CHARACTER SET utf8 ;
USE `gser_db` ;

-- -----------------------------------------------------
-- Table `gser_db`.`tipo_documento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gser_db`.`tipo_documento` ;

CREATE TABLE IF NOT EXISTS `gser_db`.`tipo_documento` (
  `tdoc_cod` INT NOT NULL AUTO_INCREMENT,
  `tdoc_desc` TEXT NOT NULL,
  PRIMARY KEY (`tdoc_cod`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gser_db`.`perfil_usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gser_db`.`perfil_usuario` ;

CREATE TABLE IF NOT EXISTS `gser_db`.`perfil_usuario` (
  `pusu_cod` INT NOT NULL AUTO_INCREMENT,
  `pusu_desc` TEXT NOT NULL,
  PRIMARY KEY (`pusu_cod`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gser_db`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gser_db`.`usuario` ;

CREATE TABLE IF NOT EXISTS `gser_db`.`usuario` (
  `usu_cod` INT NOT NULL AUTO_INCREMENT,
  `usu_nom` TEXT NOT NULL,
  `usu_ape` TEXT NULL,
  `usu_mail` TEXT NOT NULL,
  `usu_fecnac` DATE NULL,
  `usu_tdoc` INT NOT NULL DEFAULT 1,
  `usu_ndoc` VARCHAR(11) NOT NULL,
  `usu_tel` VARCHAR(7) NULL,
  `usu_movil` VARCHAR(9) NOT NULL,
  `usu_pass` TEXT NOT NULL,
  `usu_foto` VARCHAR(100) NULL,
  `usu_verificacion` INT NOT NULL DEFAULT 0,
  `usu_fecreg` DATETIME NOT NULL,
  `usu_fecmod` DATETIME NULL DEFAULT NULL,
  `usu_estado` INT NOT NULL DEFAULT 1,
  `usu_perfil` INT NOT NULL DEFAULT 2,
  PRIMARY KEY (`usu_cod`),
  CONSTRAINT `usuario_tipodocumento`
    FOREIGN KEY (`usu_tdoc`)
    REFERENCES `gser_db`.`tipo_documento` (`tdoc_cod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `usuario_perfilusuario`
    FOREIGN KEY (`usu_perfil`)
    REFERENCES `gser_db`.`perfil_usuario` (`pusu_cod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `usuario_tipodocumento_idx` ON `gser_db`.`usuario` (`usu_tdoc` ASC);

CREATE INDEX `usuario_perfilusuario_idx` ON `gser_db`.`usuario` (`usu_perfil` ASC);


-- -----------------------------------------------------
-- Table `gser_db`.`categoria_servicio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gser_db`.`categoria_servicio` ;

CREATE TABLE IF NOT EXISTS `gser_db`.`categoria_servicio` (
  `catser_cod` INT NOT NULL AUTO_INCREMENT,
  `catser_decripcion` VARCHAR(50) NOT NULL,
  `catser_img` VARCHAR(200) NULL,
  `catser_estado` INT NOT NULL DEFAULT 1,
  PRIMARY KEY (`catser_cod`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gser_db`.`servicio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gser_db`.`servicio` ;

CREATE TABLE IF NOT EXISTS `gser_db`.`servicio` (
  `ser_cod` INT NOT NULL AUTO_INCREMENT,
  `ser_codusu` INT NOT NULL,
  `ser_catsercod` INT NOT NULL,
  `ser_titulo` VARCHAR(100) NOT NULL,
  `ser_incluye` TEXT NOT NULL,
  `ser_noincluye` TEXT NULL,
  `ser_servadicionales` TEXT NULL,
  `serv_preciominimo` DECIMAL(5,2) NOT NULL,
  `ser_foto` VARCHAR(100) NULL,
  `ser_etiquetas` TEXT NULL,
  `ser_fecreg` DATETIME NOT NULL,
  `ser_fecmod` DATETIME NULL,
  `ser_estado` INT NOT NULL,
  PRIMARY KEY (`ser_cod`),
  CONSTRAINT `servicio_categoriaservicio`
    FOREIGN KEY (`ser_catsercod`)
    REFERENCES `gser_db`.`categoria_servicio` (`catser_cod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `servicio_usuario`
    FOREIGN KEY (`ser_codusu`)
    REFERENCES `gser_db`.`usuario` (`usu_cod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `servicio_categoriaservicio_idx` ON `gser_db`.`servicio` (`ser_catsercod` ASC);

CREATE INDEX `servicio_usuario_idx` ON `gser_db`.`servicio` (`ser_codusu` ASC);


-- -----------------------------------------------------
-- Table `gser_db`.`favoritos_usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gser_db`.`favoritos_usuario` ;

CREATE TABLE IF NOT EXISTS `gser_db`.`favoritos_usuario` (
  `fav_cod` INT NOT NULL AUTO_INCREMENT,
  `fav_codusu` INT NOT NULL,
  `fav_sercod` INT NOT NULL,
  `fav_fecreg` DATETIME NOT NULL,
  PRIMARY KEY (`fav_cod`),
  CONSTRAINT `favorito_usu`
    FOREIGN KEY (`fav_codusu`)
    REFERENCES `gser_db`.`usuario` (`usu_cod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `favorito_servicio`
    FOREIGN KEY (`fav_sercod`)
    REFERENCES `gser_db`.`servicio` (`ser_cod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `favorito_usu_idx` ON `gser_db`.`favoritos_usuario` (`fav_codusu` ASC);

CREATE INDEX `favorito_servicio_idx` ON `gser_db`.`favoritos_usuario` (`fav_sercod` ASC);


-- -----------------------------------------------------
-- Table `gser_db`.`datos_facturacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gser_db`.`datos_facturacion` ;

CREATE TABLE IF NOT EXISTS `gser_db`.`datos_facturacion` (
  `dfac_cod` INT NOT NULL AUTO_INCREMENT,
  `dfac_usucod` INT NOT NULL,
  `dfac_departamento` INT NOT NULL,
  `dfac_provincia` INT NOT NULL,
  `dfac_distrito` INT NOT NULL,
  `dfac_direccion` TEXT NOT NULL,
  `dfac_numero` INT NOT NULL,
  `dfac_detalle` TEXT NULL,
  `dfac_tdoc` INT NOT NULL,
  `dfac_ndoc` VARCHAR(11) NOT NULL,
  `dfac_nom` TEXT NOT NULL,
  `dfac_telefono` VARCHAR(9) NOT NULL,
  `dfac_fecreg` DATETIME NOT NULL,
  `dfac_estado` INT NOT NULL,
  PRIMARY KEY (`dfac_cod`),
  CONSTRAINT `datos_usuario`
    FOREIGN KEY (`dfac_usucod`)
    REFERENCES `gser_db`.`usuario` (`usu_cod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `datos_tipodocumento`
    FOREIGN KEY (`dfac_tdoc`)
    REFERENCES `gser_db`.`tipo_documento` (`tdoc_cod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `datos_usuario_idx` ON `gser_db`.`datos_facturacion` (`dfac_usucod` ASC);

CREATE INDEX `datos_tipodocumento_idx` ON `gser_db`.`datos_facturacion` (`dfac_tdoc` ASC);


-- -----------------------------------------------------
-- Table `gser_db`.`tarjeta_usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gser_db`.`tarjeta_usuario` ;

CREATE TABLE IF NOT EXISTS `gser_db`.`tarjeta_usuario` (
  `tar_cod` INT NOT NULL AUTO_INCREMENT,
  `tar_usucod` INT NULL,
  `tar_nrotarjeta` VARCHAR(16) NULL,
  `tar_fecvenmes` CHAR(2) NULL,
  `tar_fecvenyear` VARCHAR(4) NULL,
  `tar_nombre` VARCHAR(60) NULL,
  `tar_operador` VARCHAR(50) NULL,
  `tar_fecreg` DATETIME NULL,
  `tar_estado` INT NULL,
  PRIMARY KEY (`tar_cod`),
  CONSTRAINT `tarjetausuario_usuario`
    FOREIGN KEY (`tar_usucod`)
    REFERENCES `gser_db`.`usuario` (`usu_cod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `tarjetausuario_usuario_idx` ON `gser_db`.`tarjeta_usuario` (`tar_usucod` ASC);


-- -----------------------------------------------------
-- Table `gser_db`.`contratacion_servicio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gser_db`.`contratacion_servicio` ;

CREATE TABLE IF NOT EXISTS `gser_db`.`contratacion_servicio` (
  `cser_nrocontratacion` INT NOT NULL AUTO_INCREMENT,
  `cser_usucod` INT NOT NULL,
  `cser_sercod` INT NOT NULL,
  `cser_datosfac` INT NOT NULL,
  `cser_tarjeta` INT NOT NULL,
  `cser_codpago` TEXT NULL,
  `cser_fecreg` DATETIME NOT NULL,
  `cser_estado` INT NOT NULL,
  PRIMARY KEY (`cser_nrocontratacion`),
  CONSTRAINT `contratacionservicio_servicio`
    FOREIGN KEY (`cser_sercod`)
    REFERENCES `gser_db`.`servicio` (`ser_cod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `contratacionservicio_usuario`
    FOREIGN KEY (`cser_usucod`)
    REFERENCES `gser_db`.`usuario` (`usu_cod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `contratacionservicio_direccion`
    FOREIGN KEY (`cser_datosfac`)
    REFERENCES `gser_db`.`datos_facturacion` (`dfac_cod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `contratacionservicio_tarjeta`
    FOREIGN KEY (`cser_tarjeta`)
    REFERENCES `gser_db`.`tarjeta_usuario` (`tar_cod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `contratacionservicio_servicio_idx` ON `gser_db`.`contratacion_servicio` (`cser_sercod` ASC);

CREATE INDEX `contratacionservicio_usuario_idx` ON `gser_db`.`contratacion_servicio` (`cser_usucod` ASC);

CREATE INDEX `contratacionservicio_direccion_idx` ON `gser_db`.`contratacion_servicio` (`cser_datosfac` ASC);

CREATE INDEX `contratacionservicio_tarjeta_idx` ON `gser_db`.`contratacion_servicio` (`cser_tarjeta` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `gser_db`.`tipo_documento`
-- -----------------------------------------------------
START TRANSACTION;
USE `gser_db`;
INSERT INTO `gser_db`.`tipo_documento` (`tdoc_cod`, `tdoc_desc`) VALUES (1, 'DNI');
INSERT INTO `gser_db`.`tipo_documento` (`tdoc_cod`, `tdoc_desc`) VALUES (2, 'RUC');
INSERT INTO `gser_db`.`tipo_documento` (`tdoc_cod`, `tdoc_desc`) VALUES (3, 'RUS');
INSERT INTO `gser_db`.`tipo_documento` (`tdoc_cod`, `tdoc_desc`) VALUES (4, 'CARNET EXTRANJERIA');

COMMIT;


-- -----------------------------------------------------
-- Data for table `gser_db`.`perfil_usuario`
-- -----------------------------------------------------
START TRANSACTION;
USE `gser_db`;
INSERT INTO `gser_db`.`perfil_usuario` (`pusu_cod`, `pusu_desc`) VALUES (1, 'ADMIN');
INSERT INTO `gser_db`.`perfil_usuario` (`pusu_cod`, `pusu_desc`) VALUES (2, 'USUARIO');
INSERT INTO `gser_db`.`perfil_usuario` (`pusu_cod`, `pusu_desc`) VALUES (3, 'CONTABILIDAD');
INSERT INTO `gser_db`.`perfil_usuario` (`pusu_cod`, `pusu_desc`) VALUES (4, 'SISTEMAS');
INSERT INTO `gser_db`.`perfil_usuario` (`pusu_cod`, `pusu_desc`) VALUES (5, 'RRHH');

COMMIT;


-- -----------------------------------------------------
-- Data for table `gser_db`.`usuario`
-- -----------------------------------------------------
START TRANSACTION;
USE `gser_db`;
INSERT INTO `gser_db`.`usuario` (`usu_cod`, `usu_nom`, `usu_ape`, `usu_mail`, `usu_fecnac`, `usu_tdoc`, `usu_ndoc`, `usu_tel`, `usu_movil`, `usu_pass`, `usu_foto`, `usu_verificacion`, `usu_fecreg`, `usu_fecmod`, `usu_estado`, `usu_perfil`) VALUES (1, 'Admin', 'Admin', 'admin', '2000/01/01', 1, '00000000', NULL, '999999999', '123456', NULL, 0, '2000/01/01', NULL, 1, 1);
INSERT INTO `gser_db`.`usuario` (`usu_cod`, `usu_nom`, `usu_ape`, `usu_mail`, `usu_fecnac`, `usu_tdoc`, `usu_ndoc`, `usu_tel`, `usu_movil`, `usu_pass`, `usu_foto`, `usu_verificacion`, `usu_fecreg`, `usu_fecmod`, `usu_estado`, `usu_perfil`) VALUES (2, 'Daniel', 'Romero', 'croweloper@gmail.com', '1992/10/29', 1, '72696054', '', '931702058', '123456', NULL, 0, '2019/11/27', NULL, 1, 2);

COMMIT;


-- -----------------------------------------------------
-- Data for table `gser_db`.`categoria_servicio`
-- -----------------------------------------------------
START TRANSACTION;
USE `gser_db`;
INSERT INTO `gser_db`.`categoria_servicio` (`catser_cod`, `catser_decripcion`, `catser_img`, `catser_estado`) VALUES (1, 'Enseñanza', 'https://www.nebrija.com/medios/actualidadnebrija/wp-content/uploads/sites/2/2016/11/bbva-educacion-1920x0-c-f.jpg', 1);
INSERT INTO `gser_db`.`categoria_servicio` (`catser_cod`, `catser_decripcion`, `catser_img`, `catser_estado`) VALUES (2, 'Mantenimiento', NULL, 1);
INSERT INTO `gser_db`.`categoria_servicio` (`catser_cod`, `catser_decripcion`, `catser_img`, `catser_estado`) VALUES (3, 'Recreacion y Ocio', NULL, 1);
INSERT INTO `gser_db`.`categoria_servicio` (`catser_cod`, `catser_decripcion`, `catser_img`, `catser_estado`) VALUES (4, 'Viajes y Turismo', NULL, 1);

COMMIT;

