-- MySQL Script generated by MySQL Workbench
-- Sun Nov 10 19:39:48 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema gser_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema gser_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gser_db` DEFAULT CHARACTER SET utf8 ;
USE `gser_db` ;

-- -----------------------------------------------------
-- Table `gser_db`.`tipo_documento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gser_db`.`tipo_documento` (
  `tdoc_cod` INT NOT NULL AUTO_INCREMENT,
  `tdoc_desc` TEXT NOT NULL,
  PRIMARY KEY (`tdoc_cod`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gser_db`.`perfil_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gser_db`.`perfil_usuario` (
  `pusu_cod` INT NOT NULL AUTO_INCREMENT,
  `pusu_desc` TEXT NOT NULL,
  PRIMARY KEY (`pusu_cod`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gser_db`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gser_db`.`usuario` (
  `usu_cod` INT NOT NULL,
  `usu_nom` TEXT NOT NULL,
  `usu_ape` TEXT NULL,
  `usu_mail` TEXT NOT NULL,
  `usu_fecnac` DATE NOT NULL,
  `usu_tdoc` INT NOT NULL,
  `usu_ndoc` VARCHAR(11) NOT NULL,
  `usu_tel` VARCHAR(7) NULL,
  `usu_movil` VARCHAR(9) NOT NULL,
  `usu_pass` TEXT NOT NULL,
  `usu_foto` VARCHAR(100) NULL,
  `usu_verificacion` INT NOT NULL DEFAULT 0,
  `usu_fecreg` DATETIME NOT NULL,
  `usu_fecmod` DATETIME NULL DEFAULT NULL,
  `usu_estado` INT NOT NULL,
  `usu_perfil` INT NOT NULL,
  PRIMARY KEY (`usu_cod`),
  INDEX `usuario_tipodocumento_idx` (`usu_tdoc` ASC),
  INDEX `usuario_perfilusuario_idx` (`usu_perfil` ASC),
  CONSTRAINT `usuario_tipodocumento`
    FOREIGN KEY (`usu_tdoc`)
    REFERENCES `gser_db`.`tipo_documento` (`tdoc_cod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `usuario_perfilusuario`
    FOREIGN KEY (`usu_perfil`)
    REFERENCES `gser_db`.`perfil_usuario` (`pusu_cod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------------
-- -----------------------------------------------------------

-- -----------------------------------------------------
-- Table `gser_db`.`categoria_servicio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gser_db`.`categoria_servicio` (
  `catser_cod` INT NOT NULL AUTO_INCREMENT,
  `catser_decripcion` VARCHAR(50) NOT NULL,
  `catser_estado` INT NOT NULL DEFAULT 1,
  PRIMARY KEY (`catser_cod`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gser_db`.`servicio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gser_db`.`servicio` (
  `ser_cod` INT NOT NULL,
  `ser_codusu` INT NOT NULL,
  `ser_catsercod` INT NOT NULL,
  `ser_incluye` TEXT NOT NULL,
  `ser_noincluye` TEXT NULL,
  `ser_servadicionales` TEXT NULL,
  `serv_preciominimo` DECIMAL(5,2) NOT NULL,
  `ser_foto` VARCHAR(100) NULL,
  `ser_etiquetas` TEXT NULL,
  `ser_fecreg` DATETIME NOT NULL,
  `ser_fecmod` DATETIME NULL,
  `ser_estado` INT NOT NULL,
  PRIMARY KEY (`ser_cod`),
  INDEX `servicio_categoriaservicio_idx` (`ser_catsercod` ASC),
  INDEX `servicio_usuario_idx` (`ser_codusu` ASC),
  CONSTRAINT `servicio_categoriaservicio`
    FOREIGN KEY (`ser_catsercod`)
    REFERENCES `gser_db`.`categoria_servicio` (`catser_cod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `servicio_usuario`
    FOREIGN KEY (`ser_codusu`)
    REFERENCES `gser_db`.`usuario` (`usu_cod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gser_db`.`favoritos_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gser_db`.`favoritos_usuario` (
  `fav_cod` INT NOT NULL,
  `fav_codusu` INT NOT NULL,
  `fav_sercod` INT NOT NULL,
  `fav_fecreg` DATETIME NOT NULL,
  PRIMARY KEY (`fav_cod`),
  INDEX `favorito_usu_idx` (`fav_codusu` ASC),
  INDEX `favorito_servicio_idx` (`fav_sercod` ASC),
  CONSTRAINT `favorito_usu`
    FOREIGN KEY (`fav_codusu`)
    REFERENCES `gser_db`.`usuario` (`usu_cod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `favorito_servicio`
    FOREIGN KEY (`fav_sercod`)
    REFERENCES `gser_db`.`servicio` (`ser_cod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gser_db`.`datos_facturacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gser_db`.`datos_facturacion` (
  `dfac_cod` INT NOT NULL,
  `dfac_usucod` INT NOT NULL,
  `dfac_departamento` INT NOT NULL,
  `dfac_provincia` INT NOT NULL,
  `dfac_distrito` INT NOT NULL,
  `dfac_direccion` TEXT NOT NULL,
  `dfac_numero` INT NOT NULL,
  `dfac_detalle` TEXT NULL,
  `dfac_tdoc` INT NOT NULL,
  `dfac_ndoc` VARCHAR(11) NOT NULL,
  `dfac_nom` TEXT NOT NULL,
  `dfac_telefono` VARCHAR(9) NOT NULL,
  `dfac_fecreg` DATETIME NOT NULL,
  `dfac_estado` INT NOT NULL,
  PRIMARY KEY (`dfac_cod`),
  INDEX `datos_usuario_idx` (`dfac_usucod` ASC),
  INDEX `datos_tipodocumento_idx` (`dfac_tdoc` ASC),
  CONSTRAINT `datos_usuario`
    FOREIGN KEY (`dfac_usucod`)
    REFERENCES `gser_db`.`usuario` (`usu_cod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `datos_tipodocumento`
    FOREIGN KEY (`dfac_tdoc`)
    REFERENCES `gser_db`.`tipo_documento` (`tdoc_cod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gser_db`.`tarjeta_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gser_db`.`tarjeta_usuario` (
  `tar_cod` INT NOT NULL,
  `tar_usucod` INT NULL,
  `tar_nrotarjeta` VARCHAR(16) NULL,
  `tar_fecvenmes` CHAR(2) NULL,
  `tar_fecvenyear` VARCHAR(4) NULL,
  `tar_nombre` VARCHAR(60) NULL,
  `tar_operador` VARCHAR(50) NULL,
  `tar_fecreg` DATETIME NULL,
  `tar_estado` INT NULL,
  PRIMARY KEY (`tar_cod`),
  INDEX `tarjetausuario_usuario_idx` (`tar_usucod` ASC),
  CONSTRAINT `tarjetausuario_usuario`
    FOREIGN KEY (`tar_usucod`)
    REFERENCES `gser_db`.`usuario` (`usu_cod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gser_db`.`contratacion_servicio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gser_db`.`contratacion_servicio` (
  `cser_nrocontratacion` INT NOT NULL AUTO_INCREMENT,
  `cser_usucod` INT NOT NULL,
  `cser_sercod` INT NOT NULL,
  `cser_datosfac` INT NOT NULL,
  `cser_tarjeta` INT NOT NULL,
  `cser_codpago` TEXT NULL,
  `cser_fecreg` DATETIME NOT NULL,
  `cser_estado` INT NOT NULL,
  PRIMARY KEY (`cser_nrocontratacion`),
  INDEX `contratacionservicio_servicio_idx` (`cser_sercod` ASC),
  INDEX `contratacionservicio_usuario_idx` (`cser_usucod` ASC),
  INDEX `contratacionservicio_direccion_idx` (`cser_datosfac` ASC),
  INDEX `contratacionservicio_tarjeta_idx` (`cser_tarjeta` ASC),
  CONSTRAINT `contratacionservicio_servicio`
    FOREIGN KEY (`cser_sercod`)
    REFERENCES `gser_db`.`servicio` (`ser_cod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `contratacionservicio_usuario`
    FOREIGN KEY (`cser_usucod`)
    REFERENCES `gser_db`.`usuario` (`usu_cod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `contratacionservicio_direccion`
    FOREIGN KEY (`cser_datosfac`)
    REFERENCES `gser_db`.`datos_facturacion` (`dfac_cod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `contratacionservicio_tarjeta`
    FOREIGN KEY (`cser_tarjeta`)
    REFERENCES `gser_db`.`tarjeta_usuario` (`tar_cod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

use gser_db;

-- -------
-- --------
-- --------

INSERT INTO `usuario` (`usu_cod`, `usu_nom`, `usu_ape`, `usu_mail`, `usu_fecnac`, `usu_tdoc`, `usu_ndoc`, `usu_tel`, `usu_movil`, `usu_pass`, `usu_foto`, `usu_verificacion`, `usu_fecreg`, `usu_fecmod`, `usu_estado`, `usu_perfil`) 
			   VALUES ('1', 'Daniel', 'Romero', 'croweloper@gmail.com', '1992-10-29', '1', '72696054', NULL, '931702058', '123456', NULL, '0', '2019-11-13 00:00:00', NULL, '1', '1');



-- sp_UsuarioLogin(?,?);

drop procedure if exists sp_UsuarioLogin;

delimiter &&
create procedure sp_UsuarioLogin(in mail text,in pass text)
begin
select * from usuario where usu_mail = mail and usu_pass = pass;
end&&
delimiter ;

call sp_UsuarioLogin('croweloper@gmail.com','123456');
